# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: linuxserver.io
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd ~/apps/ga-ci-cd-nodejs
          git pull origin main
          git status
          npm install --only=prod
          pm2 restart YoutubeApp
